-- Run this once in the Supabase SQL Editor before enabling paid AI.

create table if not exists public.ai_paid_purchases (
    id bigint generated by default as identity primary key,
    stripe_session_id text not null unique,
    visitor_id text not null,
    uses integer not null check (uses > 0),
    amount_paid integer not null check (amount_paid >= 0),
    currency text not null default 'gbp',
    created_at timestamptz not null default now()
);

create index if not exists ai_paid_purchases_visitor_id_idx
    on public.ai_paid_purchases (visitor_id);

alter table public.ai_paid_purchases enable row level security;

-- The browser must never be able to read or write purchase records.
-- The Supabase Edge Function uses the service-role key internally.
revoke all on public.ai_paid_purchases from anon, authenticated;
